env:
  global:
    - secure: YuWDOwPGprL6PiBZVeGaLOCHHgC18fQ6nq617tlt7XFCkG17r/xDWq3iiAyNxNUcwsD9CkWi5aXok8SlX3rQx84XC/sya2bi0+8Frt9EztcVxgMwWuX3Ll4mFHO7HnMhazoQYRPd0b0w4s7bFY2WidxCqjsMKRgAM26Gn+6oQto=
before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly
script:
  - make clean test
after_script:
  - make docs
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
